# ESP32-C61 Device Metadata
#
# Empty [`device.driver`] tables imply `partial` support status.
#
# If you modify a driver support status, run `cargo xtask update-chip-support-table` to
# update the table in the esp-hal README.

[device]
name   = "esp32c61"
arch   = "riscv"
target = "riscv32imac-unknown-none-elf"
cores  = 1
trm    = "https://www.espressif.com/sites/default/files/documentation/esp32-c61_technical_reference_manual_en.pdf"

peripherals = [
    # { name = "DMA" },
    { name = "GPIO" },
    { name = "I2C0", interrupts = { peri = "I2C_EXT0" } },
    { name = "IO_MUX" },
    { name = "INTERRUPT_CORE0" },
    { name = "INTPRI" },
    { name = "LP_AON" },
    { name = "LP_IO" },
    { name = "LP_IO_MUX" },
    { name = "PCR" },
    # { name = "PLIC_MX" },
    { name = "SPI0" },
    { name = "SPI1" },
    { name = "SPI2", interrupts = { peri = "SPI2" } },
    { name = "SYSTEM", pac = "PCR" },
    { name = "SYSTIMER" },
    { name = "UART0", interrupts = { peri = "UART0" } },
    { name = "UART1", interrupts = { peri = "UART1" } },

    { name = "DMA_CH0", virtual = true },
    { name = "DMA_CH1", virtual = true },
    { name = "DMA_CH2", virtual = true },
 
    { name = "SW_INTERRUPT", virtual = true },
]


symbols = [
    # Additional peripherals defined by us (the developers):
    "gdma",
    # "plic",
]

memory = [{ name = "dram", start = 0x4080_0000, end = 0x4085_0000 }]

[device.gpio]
support_status = "supported"
gpio_function = 1
constant_0_input = 0x60 # TODO: Verify
constant_1_input = 0x40 # TODO: Verify
pins = [
    { pin =  0,                                                   analog = { 0 = "XTAL_32K_P" },                 lp = { 0 = "LP_UART_DTRN",    1 = "LP_GPIO0" } },
    { pin =  1,                                                   analog = { 0 = "XTAL_32K_N", 1 = "ADC1_CH0" }, lp = { 0 = "LP_UART_DSRN",    1 = "LP_GPIO1" } },
    { pin =  2,  functions = { 2 = "FSPIQ" },                                                                    lp = { 0 = "LP_UART_RTSN",    1 = "LP_GPIO2", 3 = "LP_I2C_SDA" } },
    { pin =  3,  functions = { 0 = "MTMS",       2 = "FSPIHD" },  analog = {                   1 = "ADC1_CH1" }, lp = { 0 = "LP_UART_CTSN",    1 = "LP_GPIO3", 3 = "LP_I2C_SCL" } },
    { pin =  4,  functions = { 0 = "MTDI",       2 = "FSPIWP" },  analog = {                   1 = "ADC1_CH2" }, lp = { 0 = "LP_UART_RXD_PAD", 1 = "LP_GPIO4" } },
    { pin =  5,  functions = { 0 = "MTCK" },                      analog = {                   1 = "ADC1_CH3" }, lp = { 0 = "LP_UART_TXD_PAD", 1 = "LP_GPIO5" } },
    { pin =  6,  functions = { 0 = "MTDO",       2 = "FSPICLK" } },
    { pin =  7,  functions = {                   2 = "FSPID" } },
    { pin =  8,  functions = {                   2 = "FSPICS0" }, analog = { 0 = "ZCD0" } },
    { pin =  9,                                                   analog = { 0 = "ZCD1" } },
    { pin =  10, functions = { 0 = "U0RXD",      2 = "FSPICS0" } },
    { pin =  11, functions = { 0 = "U0TXD" }},
    { pin =  12,                                                  analog = { 0 = "USB_DM" } },
    { pin =  13,                                                  analog = { 0 = "USB_DP" } },
    { pin =  22, functions = { 0 = "SDIO_DATA2" }},
    { pin =  23, functions = { 0 = "SDIO_DATA3" }},
    { pin =  24 },
    { pin =  25, functions = { 0 = "SDIO_CMD" }},
    { pin =  26, functions = { 0 = "SDIO_CLK" }},
    { pin =  27, functions = { 0 = "SDIO_DATA0" }},
    { pin =  28, functions = { 0 = "SDIO_DATA1" }}
]
input_signals = [
    { name = "U0RXD",               id = 6 },
    { name = "U0CTS",               id = 7 },
    { name = "U0DSR",               id = 8 },
    { name = "U1RXD",               id = 9 },
    { name = "U1CTS",               id = 10 },
    { name = "U1DSR",               id = 11 },
    { name = "I2S_MCLK",            id = 12 },
    { name = "I2SO_BCK",            id = 13 },
    { name = "I2SO_WS",             id = 14 },
    { name = "I2SI_SD",             id = 15 },
    { name = "I2SI_BCK",            id = 16 },
    { name = "I2SI_WS",             id = 17 },
    { name = "CPU_GPIO_IN0",        id = 27 },
    { name = "CPU_GPIO_IN1",        id = 28 },
    { name = "CPU_GPIO_IN2",        id = 29 },
    { name = "CPU_GPIO_IN3",        id = 30 },
    { name = "CPU_GPIO_IN4",        id = 31 },
    { name = "CPU_GPIO_IN5",        id = 32 },
    { name = "CPU_GPIO_IN6",        id = 33 },
    { name = "CPU_GPIO_IN7",        id = 34 },
    { name = "USB_JTAG_TDO_BRIDGE", id = 35 },
    { name = "I2CEXT0_SCL",         id = 46 },
    { name = "I2CEXT0_SDA",         id = 47 },
    # { name = "PARL_RX_DATA0",       id = 48 },
    # { name = "PARL_RX_DATA1",       id = 49 },
    # { name = "PARL_RX_DATA2",       id = 50 },
    # { name = "PARL_RX_DATA3",       id = 51 },
    # { name = "PARL_RX_DATA4",       id = 52 },
    # { name = "PARL_RX_DATA5",       id = 53 },
    # { name = "PARL_RX_DATA6",       id = 54 },
    # { name = "PARL_RX_DATA7",       id = 55 },
    { name = "FSPICLK",             id = 64 },
    { name = "FSPIQ",               id = 65 },
    { name = "FSPID",               id = 66 },
    { name = "FSPIHD",              id = 67 },
    { name = "FSPIWP",              id = 68 },
    { name = "FSPICS0",             id = 69 },
    { name = "U2RXD",               id = 72 },
    { name = "U2CTS",               id = 73 },
    { name = "U2DSR",               id = 74 },
    # { name = "RMT_SIG_1",           id = 65 },
    # { name = "TWAI0_RX",            id = 66 },
    # { name = "TWAI1_RX",            id = 70 },
    # { name = "PCNT0_RST",           id = 76 },
    # { name = "PCNT1_RST",           id = 77 },
    # { name = "PCNT2_RST",           id = 78 },
    # { name = "PCNT3_RST",           id = 79 },
    # { name = "PWM0_SYNC0",          id = 80 },
    # { name = "PWM0_SYNC1",          id = 81 },
    # { name = "PWM0_SYNC2",          id = 82 },
    # { name = "PWM0_F0",             id = 83 },
    # { name = "PWM0_F1",             id = 84 },
    # { name = "PWM0_F2",             id = 85 },
    # { name = "PWM0_CAP0",           id = 86 },
    # { name = "PWM0_CAP1",           id = 87 },
    # { name = "PWM0_CAP2",           id = 88 },
    { name = "SIG_IN_FUNC97",       id = 97 },
    { name = "SIG_IN_FUNC98",       id = 98 },
    { name = "SIG_IN_FUNC99",       id = 99 },
    { name = "SIG_IN_FUNC100",      id = 100 },
    # { name = "PCNT0_SIG_CH0",       id = 101 },
    # { name = "PCNT0_SIG_CH1",       id = 102 },
    # { name = "PCNT0_CTRL_CH0",      id = 103 },
    # { name = "PCNT0_CTRL_CH1",      id = 104 },
    # { name = "PCNT1_SIG_CH0",       id = 105 },
    # { name = "PCNT1_SIG_CH1",       id = 106 },
    # { name = "PCNT1_CTRL_CH0",      id = 107 },
    # { name = "PCNT1_CTRL_CH1",      id = 108 },
    # { name = "PCNT2_SIG_CH0",       id = 109 },
    # { name = "PCNT2_SIG_CH1",       id = 110 },
    # { name = "PCNT2_CTRL_CH0",      id = 111 },
    # { name = "PCNT2_CTRL_CH1",      id = 112 },
    # { name = "PCNT3_SIG_CH0",       id = 113 },
    # { name = "PCNT3_SIG_CH1",       id = 114 },
    # { name = "PCNT3_CTRL_CH0",      id = 115 },
    # { name = "PCNT3_CTRL_CH1",      id = 116 },

    { name = "SDIO_CLK" },
    { name = "SDIO_CMD" },
    { name = "SDIO_DATA0" },
    { name = "SDIO_DATA1" },
    { name = "SDIO_DATA2" },
    { name = "SDIO_DATA3" },

    { name = "MTDI" },
    { name = "MTDO" },
    { name = "MTCK" },
    { name = "MTMS" },
]
output_signals = [
    { name = "LEDC_LS_SIG0",     id = 0 },
    { name = "LEDC_LS_SIG1",     id = 1 },
    { name = "LEDC_LS_SIG2",     id = 2 },
    { name = "LEDC_LS_SIG3",     id = 3 },
    { name = "LEDC_LS_SIG4",     id = 4 },
    { name = "LEDC_LS_SIG5",     id = 5 },
    { name = "U0TXD",            id = 6 },
    { name = "U0RTS",            id = 7 },
    { name = "U0DTR",            id = 8 },
    { name = "U1TXD",            id = 9 },
    { name = "U1RTS",            id = 10 },
    { name = "U1DTR",            id = 11 },
    { name = "I2S_MCLK",         id = 12 },
    { name = "I2SO_BCK",         id = 13 },
    { name = "I2SO_WS",          id = 14 },
    { name = "I2SO_SD",          id = 15 },
    { name = "I2SI_BCK",         id = 16 },
    { name = "I2SI_WS",          id = 17 },
    { name = "I2SO_SD1",         id = 18 },
    { name = "CPU_GPIO_OUT0",    id = 27 },
    { name = "CPU_GPIO_OUT1",    id = 28 },
    { name = "CPU_GPIO_OUT2",    id = 29 },
    { name = "CPU_GPIO_OUT3",    id = 30 },
    { name = "CPU_GPIO_OUT4",    id = 31 },
    { name = "CPU_GPIO_OUT5",    id = 32 },
    { name = "CPU_GPIO_OUT6",    id = 33 },
    { name = "CPU_GPIO_OUT7",    id = 34 },
    { name = "I2CEXT0_SCL",      id = 46 },
    { name = "I2CEXT0_SDA",      id = 47 },
    # { name = "PARL_TX_DATA0",    id = 48 },
    # { name = "PARL_TX_DATA1",    id = 49 },
    # { name = "PARL_TX_DATA2",    id = 50 },
    # { name = "PARL_TX_DATA3",    id = 51 },
    # { name = "PARL_TX_DATA4",    id = 52 },
    # { name = "PARL_TX_DATA5",    id = 53 },
    # { name = "PARL_TX_DATA6",    id = 54 },
    # { name = "PARL_TX_DATA7",    id = 55 },
    { name = "FSPICLK",          id = 64 },
    { name = "FSPIQ",            id = 65 },
    { name = "FSPID",            id = 66 },
    { name = "FSPIHD",           id = 67 },
    { name = "FSPIWP",           id = 68 },
    { name = "FSPICS0",          id = 69 },
    { name = "U2RXD",            id = 72 },
    { name = "U2CTS",            id = 73 },
    { name = "U2DSR",            id = 74 },
    # { name = "RMT_SIG_1",        id = 65 },
    # { name = "TWAI0_TX",         id = 66 },
    # { name = "TWAI0_BUS_OFF_ON", id = 67 },
    # { name = "TWAI0_CLKOUT",     id = 68 },
    # { name = "TWAI0_STANDBY",    id = 69 },
    # { name = "TWAI1_TX",         id = 70 },
    # { name = "TWAI1_BUS_OFF_ON", id = 71 },
    # { name = "TWAI1_CLKOUT",     id = 72 },
    # { name = "TWAI1_STANDBY",    id = 73 },
    # { name = "GPIO_SD0",         id = 76 },
    # { name = "GPIO_SD1",         id = 77 },
    # { name = "GPIO_SD2",         id = 78 },
    # { name = "GPIO_SD3",         id = 79 },
    # { name = "PWM0_0A",          id = 80 },
    # { name = "PWM0_0B",          id = 81 },
    # { name = "PWM0_1A",          id = 82 },
    # { name = "PWM0_1B",          id = 83 },
    # { name = "PWM0_2A",          id = 84 },
    # { name = "PWM0_2B",          id = 85 },
    # { name = "PARL_TX_CS",       id = 86 },
    { name = "SIG_IN_FUNC97",    id = 97 },
    { name = "SIG_IN_FUNC98",    id = 98 },
    { name = "SIG_IN_FUNC99",    id = 99 },
    { name = "SIG_IN_FUNC100",   id = 100 },
    { name = "FSPICS1",          id = 102 },
    { name = "FSPICS2",          id = 103 },
    { name = "FSPICS3",          id = 104 },
    { name = "FSPICS4",          id = 105 },
    { name = "FSPICS5",          id = 106 },
    { name = "GPIO",             id = 256 }, # TODO: Verify
]

# TODO: Verify
[device.i2c_master]
support_status = "supported"
instances = [
    { name = "i2c0", sys_instance = "I2cExt0", scl = "I2CEXT0_SCL", sda = "I2CEXT0_SDA" },
]
has_fsm_timeouts = true
has_hw_bus_clear = true
ll_intr_mask = 0x3fff # TODO: verify
## TRM/22.4.3
fifo_size = 32
has_bus_timeout_enable = true
max_bus_timeout = 0x1F
can_estimate_nack_reason = true
has_conf_update = true
has_reliable_fsm_reset = true
has_arbitration_en = true
has_tx_fifo_watermark = true
bus_timeout_is_exponential = true

[device.i2c_slave]
support_status = "not_supported"

[device.interrupts]
support_status = "partial"
status_registers = 3 # TODO: Verify

[device.spi_master]
support_status = "supported"
instances = [
    { name = "spi2", sys_instance = "Spi2", sclk = "FSPICLK", sio = ["FSPID", "FSPIQ", "FSPIWP", "FSPIHD"], cs = ["FSPICS0", "FSPICS1", "FSPICS2", "FSPICS3", "FSPICS4", "FSPICS5"] },
]

[device.spi_slave]
instances = [
    { name = "spi2", sys_instance = "Spi2", sclk = "FSPICLK",  mosi = "FSPID",  miso = "FSPIQ",  cs = "FSPICS0" },
]

[device.uart]
support_status = "supported"
instances = [
    { name = "uart0", sys_instance = "Uart0", tx = "U0TXD", rx = "U0RXD", cts = "U0CTS", rts = "U0RTS" },
    { name = "uart1", sys_instance = "Uart1", tx = "U1TXD", rx = "U1RXD", cts = "U1CTS", rts = "U1RTS" },
]

## Miscellaneous
[device.dma]
[device.io_mux]
[device.systimer]
