# ESP32-C61 Device Metadata
#
# Empty [`device.driver`] tables imply `partial` support status.
#
# If you modify a driver support status, run `cargo xtask update-chip-support-table` to
# update the table in the esp-hal README.

[device]
name   = "esp32c61"
arch   = "riscv"
target = "riscv32imac-unknown-none-elf"
cores  = 1
trm    = "https://www.espressif.com/sites/default/files/documentation/esp32-c61_technical_reference_manual_en.pdf"

peripherals = []

symbols = []

memory = [{ name = "dram", start = 0x4080_0000, end = 0x4085_0000 }]
